### ISSUE TITLE
Cursor is not `pointer` when the "anchor point" (top left) is not part of the piece

### ISSUE THREAD

**Issue by tscizzle** [tscizzle/WebBlokus#3]
Consider the piece
```
[['O', 'X'],
 ['X', 'X']]
```

The clicked position on the board is where to put the top left corner of this piece, but the top left has an `'O'`, so when you're placing it, you're not clicking a spot where the piece actually ends up sitting.

**Comment by kleinab** [comment]
closed with #bbc5820 from Blokus
